### ISSUE TITLE
Reset cause is not created when the script is used

### ISSUE THREAD

**Issue by doditaly** [troglobit/watchdogd#8] opened 2018-04-18 12:49 UTC
When a script or global script is used, the reset cause is not written in the watchdog.state file.
It is a shame.

**Comment by troglobit** [comment] 2018-04-18 13:46
That's by design. Not all users want their board to reset when WARN trigger level is reached, so not really a good idea to default to set reset cause.  But sure, there should be a way to delegate to the plugin to perform a reset, including saving reset cause, from the the script.  Maybe look at return value from script?

**Comment by doditaly** [comment] 2018-04-18 14:08
In my case, I use the script for saving system status, like log files that are located in a ramfs, and then for rebooting the system sending a reset signal to the switching power supply IC. In this way all the hardware components on the board reboot.
Using the return value of the script is not applicable in my application.
It could be enough for me that watchdogd writes the reset cause only when the critical level is reached.

**Comment by troglobit** [comment] 2018-04-18 14:55
I see. Curious, why not connect the kernel reboot to the switching power supply reset signal?

It's difficult to accommodate all possible embedded systems from an open source component like this. I guess there will be certain (integration) patches you'll have to maintain yourself.

**Comment by doditaly** [comment] 2018-04-18 15:51
I use this reboot method because in the "real world" the device will be turned off (or rebooted) always switching off the power supply instead of using "shutdown" command. So I prefer using the same reboot method for all the situation, 
included the watchdogd reboot.
Anyway, you are right, It is difficult to accommodate all possible embedded systems, so, for my case, is better to delegate to the script the "reset cause" saving. Are you agree?

**Comment by troglobit** [comment] 2018-05-12 16:50
Closing.  I will add a new command (or modify an existing, not decided yet) to `watchdogctl` to allow remote processes, including the scripts, to record a reset reason (and optionally) perform a reset via the WDT.

**Closed by troglobit** 2018-05-12 16:50 UTC
