### ISSUE TITLE
WDT does not support PWR fail condition, treating as card reset.

### ISSUE THREAD

**Issue by pietercardoen** [troglobit/watchdogd#10] opened 2018-04-27 11:49 UTC
What does this remark mean:

WDT does not support PWR fail condition, treating as card reset.

BR
Pieter

**Comment by troglobit** [comment] 2018-04-28 08:43
It means the WDT (or its driver) does not support the `WDIOF_POWERUNDER` capability to detect if the reason for a reset was a power failure. This is one of the causes watchdogd attempts to figure out at boot.  See the `docs/DESIGN.md` document for more info on this.

**Comment by troglobit** [comment] 2018-05-10 21:03
The warning remark you got when trying out `ex1` has been removed as of ace1e6c and is now only shown once for each instance of `watchdogd`.

I guess we can close this issue too, unless you're interested in the i.MX2 WDT driver patch?

**Comment by troglobit** [comment] 2018-05-12 16:48
No replies, closing.

**Closed by troglobit** 2018-05-12 16:48 UTC

**Comment by pietercardoen** [comment] 2018-09-17 08:52
Thanks for your effort. Due to other priorities, I hadn't got time to look at this. I am interested in the i.MX2 WDT driver patch. Do you have it available?

Thanks
Pieter

**Comment by troglobit** [comment] 2018-09-17 11:29
This is from an older linux-3.0 tree I had on my machine, but I think you get the gist of it:
```diff
        case WDIOC_GETSTATUS:
-       case WDIOC_GETBOOTSTATUS:
                return put_user(0, p);
 
+       case WDIOC_GETBOOTSTATUS:
+               val = __raw_readw(imx2_wdt.base + IMX2_WDT_WRSR);
+               if (val & IMX2_WDT_WRSR_TOUT)
+                       new_value = WDIOF_CARDRESET;
+               else if (val & IMX2_WDT_WRSR_PWR)
+                       new_value = WDIOF_POWERUNDER;
+               else
+                       new_value = 0;
+               return put_user(new_value, p);
+
```
